### ISSUE TITLE
tfrecords

### ISSUE THREAD

**Issue by JingpengSun** [luuil/Tensorflow-Audio-Classification#2]
hello, thank you for your interesting work.
I follow you steps and get the results you said.
now, I'm going to check its performance on my own data.
Could you tell me how to produce the three tfrecord files,
that is, urban_sound_test.tfrecords, urban_sound_tfrecords, urban_sound_val.tfrecords
thanks!

**Comment by JingpengSun** [comment]
I find how to do it.
By the way, there is a another confusion about the dataset split into train、val and test three part
with a probability 0.7、0.1 and 0.2 respectively.
I'm wondering how to make sure the distribution of selected three parts is same as original distribution if the samples in different classes are unbanlanced? 
I looked inside the [split [code]](https://github.com/luuil/Tensorflow-Audio-Classification/blob/9a82c014c2e87301ce74c1d495b98695f9261004/audio/audio_util.py#L77)
and found it did it very well (selected part' s distribution almost same as the original). 
But I did not found how it did this (e.g. selected sample class by class), 
Do you have any ideas about it?

**Comment by luuil** [comment]
Sorry for late response, do you want to known how function [train_test_val_split](https://github.com/luuil/Tensorflow-Audio-Classification/blob/9a82c014c2e87301ce74c1d495b98695f9261004/audio/audio_util.py#L77) works? You may noticed [line 89](https://github.com/luuil/Tensorflow-Audio-Classification/blob/9a82c014c2e87301ce74c1d495b98695f9261004/audio/audio_util.py#L89), it's from sklearn.model_selection, so you may refer to [sklearn.model_selection.train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).

**Comment by xiaofengo** [comment]
> hello, thank you for your interesting work.
> I follow you steps and get the results you said.
> now, I'm going to check its performance on my own data.
> Could you tell me how to produce the three tfrecord files,
> that is, urban_sound_test.tfrecords, urban_sound_tfrecords, urban_sound_val.tfrecords
> thanks!

hi,I have the same problem. Have you solved it? Is there a source code for generating these three files separately?
